# Site settings
title:          Blog Theme
description:    "Soham Patil blog theme"
baseurl:        ""
url:            "https://sohampatil.in"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Soham Patil
  url:          https://sohampatil.in
  email:        hi@sohampatil.in

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, blogtheme.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-blogtheme